In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
import plotly.express as px
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Users\admin\Downloads\IndianWeatherRepository.csv")
df

,country,location_name,region,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,India,Ashoknagar,Madhya Pradesh,24.57,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,12.6,18.5,1,2,05:59 AM,06:41 PM,05:42 PM,03:38 AM,Waxing Gibbous,93
1,India,Raisen,Madhya Pradesh,23.33,77.80,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,10.7,14.2,1,1,06:00 AM,06:40 PM,05:39 PM,03:41 AM,Waxing Gibbous,93
2,India,Chhindwara,Madhya Pradesh,22.07,78.93,Asia/Kolkata,1693286100,2023-08-29 10:45,26.3,79.3,...,16.8,20.7,2,2,05:56 AM,06:34 PM,05:32 PM,03:39 AM,Waxing Gibbous,93
3,India,Betul,Madhya Pradesh,21.86,77.93,Asia/Kolkata,1693286100,2023-08-29 10:45,25.6,78.1,...,4.9,6.6,1,1,06:00 AM,06:38 PM,05:36 PM,03:43 AM,Waxing Gibbous,93
4,India,Hoshangabad,Madhya Pradesh,22.75,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.2,81.0,...,11.4,14.8,1,1,06:01 AM,06:39 PM,05:38 PM,03:42 AM,Waxing Gibbous,93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115557,India,Niwari,Uttar Pradesh,28.88,77.53,Asia/Kolkata,1711815300,2024-03-30 21:45,29.0,84.2,...,50.5,129.9,3,6,06:12 AM,06:37 PM,11:28 PM,08:52 AM,Waning Gibbous,80
115558,India,Saitual,Mizoram,23.97,92.58,Asia/Kolkata,1711815300,2024-03-30 21:45,18.3,64.9,...,16.2,18.0,2,2,05:14 AM,05:35 PM,10:11 PM,08:02 AM,Waning Gibbous,80
115559,India,Ranipet,Tamil Nadu,12.93,79.33,Asia/Kolkata,1711815300,2024-03-30 21:45,25.4,77.8,...,8.2,13.2,1,1,06:10 AM,06:24 PM,10:41 PM,09:21 AM,Waning Gibbous,80
115560,India,Tenkasi,Tamil Nadu,8.97,77.30,Asia/Kolkata,1711815300,2024-03-30 21:45,31.0,87.8,...,9.4,11.8,1,1,06:19 AM,06:31 PM,10:41 PM,09:37 AM,Waning Gibbous,80
115561,India,Pendra,Maharashtra,21.93,74.15,Asia/Kolkata,1711815300,2024-03-30 21:45,27.8,82.0,...,21.3,28.8,2,2,06:28 AM,06:48 PM,11:23 PM,09:23 AM,Waning Gibbous,80

In [3]:
columns_to_drop = ['cloud','visibility_km','uv_index','country','region','timezone','last_updated_epoch','temperature_fahrenheit','wind_direction','wind_kph','wind_degree','pressure_in','precip_in','feels_like_fahrenheit','feels_like_celsius','visibility_miles','gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination']
df.drop(columns= columns_to_drop,inplace = True)
df

,location_name,latitude,longitude,last_updated,temperature_celsius,condition_text,wind_mph,pressure_mb,precip_mm,humidity
0,Ashoknagar,24.57,77.72,2023-08-29 10:45,27.5,Partly cloudy,12.8,1008.0,0.0,67
1,Raisen,23.33,77.80,2023-08-29 10:45,27.5,Sunny,9.6,1008.0,0.0,70
2,Chhindwara,22.07,78.93,2023-08-29 10:45,26.3,Partly cloudy,11.4,1009.0,0.0,70
3,Betul,21.86,77.93,2023-08-29 10:45,25.6,Cloudy,10.5,1009.0,0.0,76
4,Hoshangabad,22.75,77.72,2023-08-29 10:45,27.2,Cloudy,10.1,1009.0,0.0,74
...,...,...,...,...,...,...,...,...,...,...
115557,Niwari,28.88,77.53,2024-03-30 21:45,29.0,Mist,2.2,1011.0,0.0,45
115558,Saitual,23.97,92.58,2024-03-30 21:45,18.3,Clear,3.6,1014.0,0.0,79
115559,Ranipet,12.93,79.33,2024-03-30 21:45,25.4,Clear,6.3,1014.0,0.0,57
115560,Tenkasi,8.97,77.30,2024-03-30 21:45,31.0,Mist,2.2,1013.0,0.0,66
115561,Pendra,21.93,74.15,2024-03-30 21:45,27.8,Clear,6.7,1012.0,0.0,23

In [4]:
cat_cols= df.select_dtypes(include = ['object']).columns
cat_cols

Index(['location_name', 'last_updated', 'condition_text'], dtype='object')

In [5]:
num_cols = df.select_dtypes(include = ['number']).columns
num_cols

Index(['latitude', 'longitude', 'temperature_celsius', 'wind_mph',
       'pressure_mb', 'precip_mm', 'humidity'],
      dtype='object')

In [6]:
clear_data = df[df['condition_text'] == 'Clear']

clear_data

,location_name,latitude,longitude,last_updated,temperature_celsius,condition_text,wind_mph,pressure_mb,precip_mm,humidity
573,Seoni,22.08,79.53,2023-08-30 08:45,21.6,Clear,5.4,1007.0,0.0,91
1095,Chhindwara,22.07,78.93,2023-08-31 05:15,21.4,Clear,4.7,1009.0,0.0,75
1096,Betul,21.86,77.93,2023-08-31 05:15,21.0,Clear,2.7,1009.0,0.0,87
1097,Hoshangabad,22.75,77.72,2023-08-31 05:15,23.0,Clear,5.4,1008.0,0.0,84
1099,Jabalpur,23.17,79.95,2023-08-31 05:15,22.7,Clear,3.1,1008.0,0.0,79
...,...,...,...,...,...,...,...,...,...,...
115130,West Godavari,16.70,81.10,2024-03-30 21:30,29.0,Clear,3.8,1012.0,0.0,79
115254,Nandi Hills,13.33,77.65,2024-03-30 21:30,28.0,Clear,11.9,1018.0,0.0,25
115340,Kolar,13.13,78.13,2024-03-30 21:30,28.0,Clear,11.9,1018.0,0.0,25
115350,Bangalore,12.98,77.58,2024-03-30 21:30,28.0,Clear,11.9,1018.0,0.0,25
115351,Tumkur,13.34,77.10,2024-03-30 21:30,28.0,Clear,11.9,1018.0,0.0,25

In [7]:
count = df["condition_text"].value_counts()
count

condition_text
Clear                                          46245
Clear                                          23055
Mist                                           16371
Partly cloudy                                   9181
Patchy rain possible                            5126
Light rain shower                               2914
Partly Cloudy                                   2128
Fog                                             2014
Overcast                                        1816
Cloudy                                          1367
Patchy rain nearby                              1260
Sunny                                            772
Light rain                                       497
Moderate or heavy rain shower                    402
Overcast                                         332
Light drizzle                                    270
Cloudy                                           253
Moderate or heavy rain with thunder              236
Patchy light drizzle                             233
Moderate rain                                    175
Patchy light rain                                145
Patchy light rain with thunder                   112
Moderate rain at times                            93
Thundery outbreaks possible                       74
Light freezing rain                               65
Heavy rain                                        57
Moderate or heavy snow showers                    45
Patchy light rain in area with thunder            39
Torrential rain shower                            34
Heavy snow                                        33
Thundery outbreaks in nearby                      32
Light snow showers                                30
Patchy snow nearby                                26
Patchy light snow                                 25
Light snow                                        18
Light sleet                                       15
Patchy moderate snow                              14
Moderate or heavy snow in area with thunder       11
Light sleet showers                                8
Patchy heavy snow                                  6
Patchy light snow with thunder                     6
Moderate or heavy sleet                            5
Patchy sleet nearby                                5
Patchy snow possible                               5
Patchy light snow in area with thunder             4
Heavy rain at times                                4
Moderate snow                                      2
Moderate or heavy rain in area with thunder        1
Moderate or heavy snow with thunder                1
Name: count, dtype: int64

In [8]:
df["condition_text"].nunique()

49

In [9]:
count = df["condition_text"].str.strip().value_counts()
unique_values = df["condition_text"].unique()
df['condition_text'] = df['condition_text'].str.lower()
print(unique_values)

['Partly cloudy' 'Sunny' 'Cloudy' 'Mist' 'Patchy rain possible' 'Overcast'
 'Patchy light rain with thunder' 'Light rain shower'
 'Moderate or heavy rain shower' 'Clear' 'Light rain'
 'Torrential rain shower' 'Fog' 'Thundery outbreaks possible'
 'Patchy light drizzle' 'Moderate rain' 'Patchy light rain'
 'Moderate rain at times' 'Heavy rain' 'Heavy rain at times'
 'Light drizzle' 'Moderate or heavy rain with thunder'
 'Patchy snow possible' 'Moderate or heavy snow showers'
 'Light snow showers' 'Moderate or heavy snow with thunder'
 'Patchy light snow with thunder' 'Light sleet' 'Light freezing rain'
 'Patchy light snow' 'Patchy moderate snow' 'Light snow' 'Moderate snow'
 'Overcast ' 'Clear ' 'Cloudy ' 'Partly Cloudy ' 'Patchy rain nearby'
 'Thundery outbreaks in nearby' 'Heavy snow'
 'Patchy light snow in area with thunder'
 'Patchy light rain in area with thunder' 'Light sleet showers'
 'Moderate or heavy snow in area with thunder'
 'Moderate or heavy rain in area with thunder' 'Patchy heavy snow'
 'Patchy snow nearby' 'Patchy sleet nearby' 'Moderate or heavy sleet']

In [10]:
threshold = 1000
repl = count [count>=threshold].index
repl

Index(['Clear', 'Mist', 'Partly cloudy', 'Patchy rain possible',
       'Light rain shower', 'Overcast', 'Partly Cloudy', 'Fog', 'Cloudy',
       'Patchy rain nearby'],
      dtype='object', name='condition_text')

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le=LabelEncoder()

In [13]:
le.fit(repl)

LabelEncoder()

In [14]:
le.transform(repl)

array([0, 4, 7, 9, 3, 5, 6, 2, 1, 8])

In [15]:
le.classes_

array(['Clear', 'Cloudy', 'Fog', 'Light rain shower', 'Mist', 'Overcast',
       'Partly Cloudy', 'Partly cloudy', 'Patchy rain nearby',
       'Patchy rain possible'], dtype=object)

In [16]:
df.dtypes

location_name           object
latitude               float64
longitude              float64
last_updated            object
temperature_celsius    float64
condition_text          object
wind_mph               float64
pressure_mb            float64
precip_mm              float64
humidity                 int64
dtype: object

In [17]:
df.index

RangeIndex(start=0, stop=115562, step=1)

In [18]:
df['last_updated']=pd.to_datetime(df['last_updated'])

In [19]:
df

,location_name,latitude,longitude,last_updated,temperature_celsius,condition_text,wind_mph,pressure_mb,precip_mm,humidity
0,Ashoknagar,24.57,77.72,2023-08-29 10:45:00,27.5,partly cloudy,12.8,1008.0,0.0,67
1,Raisen,23.33,77.80,2023-08-29 10:45:00,27.5,sunny,9.6,1008.0,0.0,70
2,Chhindwara,22.07,78.93,2023-08-29 10:45:00,26.3,partly cloudy,11.4,1009.0,0.0,70
3,Betul,21.86,77.93,2023-08-29 10:45:00,25.6,cloudy,10.5,1009.0,0.0,76
4,Hoshangabad,22.75,77.72,2023-08-29 10:45:00,27.2,cloudy,10.1,1009.0,0.0,74
...,...,...,...,...,...,...,...,...,...,...
115557,Niwari,28.88,77.53,2024-03-30 21:45:00,29.0,mist,2.2,1011.0,0.0,45
115558,Saitual,23.97,92.58,2024-03-30 21:45:00,18.3,clear,3.6,1014.0,0.0,79
115559,Ranipet,12.93,79.33,2024-03-30 21:45:00,25.4,clear,6.3,1014.0,0.0,57
115560,Tenkasi,8.97,77.30,2024-03-30 21:45:00,31.0,mist,2.2,1013.0,0.0,66
115561,Pendra,21.93,74.15,2024-03-30 21:45:00,27.8,clear,6.7,1012.0,0.0,23

In [20]:
df.dtypes

location_name                  object
latitude                      float64
longitude                     float64
last_updated           datetime64[ns]
temperature_celsius           float64
condition_text                 object
wind_mph                      float64
pressure_mb                   float64
precip_mm                     float64
humidity                        int64
dtype: object

In [21]:
df['last_updated'].dt.year

0         2023
1         2023
2         2023
3         2023
4         2023
          ...
115557    2024
115558    2024
115559    2024
115560    2024
115561    2024
Name: last_updated, Length: 115562, dtype: int32

In [22]:
df['Target']=df.shift(-1)['temperature_celsius']

In [23]:
df

,location_name,latitude,longitude,last_updated,temperature_celsius,condition_text,wind_mph,pressure_mb,precip_mm,humidity,Target
0,Ashoknagar,24.57,77.72,2023-08-29 10:45:00,27.5,partly cloudy,12.8,1008.0,0.0,67,27.5
1,Raisen,23.33,77.80,2023-08-29 10:45:00,27.5,sunny,9.6,1008.0,0.0,70,26.3
2,Chhindwara,22.07,78.93,2023-08-29 10:45:00,26.3,partly cloudy,11.4,1009.0,0.0,70,25.6
3,Betul,21.86,77.93,2023-08-29 10:45:00,25.6,cloudy,10.5,1009.0,0.0,76,27.2
4,Hoshangabad,22.75,77.72,2023-08-29 10:45:00,27.2,cloudy,10.1,1009.0,0.0,74,25.9
...,...,...,...,...,...,...,...,...,...,...,...
115557,Niwari,28.88,77.53,2024-03-30 21:45:00,29.0,mist,2.2,1011.0,0.0,45,18.3
115558,Saitual,23.97,92.58,2024-03-30 21:45:00,18.3,clear,3.6,1014.0,0.0,79,25.4
115559,Ranipet,12.93,79.33,2024-03-30 21:45:00,25.4,clear,6.3,1014.0,0.0,57,31.0
115560,Tenkasi,8.97,77.30,2024-03-30 21:45:00,31.0,mist,2.2,1013.0,0.0,66,27.8
115561,Pendra,21.93,74.15,2024-03-30 21:45:00,27.8,clear,6.7,1012.0,0.0,23,NaN

In [24]:
df.ffill()

,location_name,latitude,longitude,last_updated,temperature_celsius,condition_text,wind_mph,pressure_mb,precip_mm,humidity,Target
0,Ashoknagar,24.57,77.72,2023-08-29 10:45:00,27.5,partly cloudy,12.8,1008.0,0.0,67,27.5
1,Raisen,23.33,77.80,2023-08-29 10:45:00,27.5,sunny,9.6,1008.0,0.0,70,26.3
2,Chhindwara,22.07,78.93,2023-08-29 10:45:00,26.3,partly cloudy,11.4,1009.0,0.0,70,25.6
3,Betul,21.86,77.93,2023-08-29 10:45:00,25.6,cloudy,10.5,1009.0,0.0,76,27.2
4,Hoshangabad,22.75,77.72,2023-08-29 10:45:00,27.2,cloudy,10.1,1009.0,0.0,74,25.9
...,...,...,...,...,...,...,...,...,...,...,...
115557,Niwari,28.88,77.53,2024-03-30 21:45:00,29.0,mist,2.2,1011.0,0.0,45,18.3
115558,Saitual,23.97,92.58,2024-03-30 21:45:00,18.3,clear,3.6,1014.0,0.0,79,25.4
115559,Ranipet,12.93,79.33,2024-03-30 21:45:00,25.4,clear,6.3,1014.0,0.0,57,31.0
115560,Tenkasi,8.97,77.30,2024-03-30 21:45:00,31.0,mist,2.2,1013.0,0.0,66,27.8
115561,Pendra,21.93,74.15,2024-03-30 21:45:00,27.8,clear,6.7,1012.0,0.0,23,27.8

In [25]:
from sklearn.linear_model import Ridge

In [26]:
df.corr(numeric_only=True)

,latitude,longitude,temperature_celsius,wind_mph,pressure_mb,precip_mm,humidity,Target
latitude,1.000000,0.076130,-0.508373,-0.184791,0.198815,-0.064091,-0.306976,-0.392312
longitude,0.076130,1.000000,-0.109316,-0.267551,-0.013229,0.041448,0.291353,-0.078985
temperature_celsius,-0.508373,-0.109316,1.000000,0.249179,-0.716753,0.061829,0.088251,0.717651
wind_mph,-0.184791,-0.267551,0.249179,1.000000,-0.180021,0.057535,-0.098117,0.185023
pressure_mb,0.198815,-0.013229,-0.716753,-0.180021,1.000000,-0.165893,-0.301725,-0.570380
precip_mm,-0.064091,0.041448,0.061829,0.057535,-0.165893,1.000000,0.174666,0.065227
humidity,-0.306976,0.291353,0.088251,-0.098117,-0.301725,0.174666,1.000000,0.133852
Target,-0.392312,-0.078985,0.717651,0.185023,-0.570380,0.065227,0.133852,1.000000

In [27]:
rr=Ridge(alpha=.1)

In [28]:
predictor=df.columns[~df.columns.isin(['location_name','latitude','condition_text','longitude','last_updated','precip_mm','Target'])]

In [29]:
predictor

Index(['temperature_celsius', 'wind_mph', 'pressure_mb', 'humidity'], dtype='object')

In [30]:
def backtest(df,model,predictor,start=3650,step=90):
    all_prediction=[]
    for i in range(start,df.shape[0],step):
        train=df.iloc[:i,:]
        test=df.iloc[i:(i+step),:]
        
        model.fit(train[predictor],train['Target'])
        
        preds=model.predict(test[predictor])
        
        preds=pd.Series(preds,index=test.index)
        combined=pd.concat([test['Target'],preds],axis=1)
        
        combined.columns=['actual','prediction']
        
        combined['diff']=(combined['prediction']-combined['actual']).abs()
        
        all_prediction.append(round(combined))
    return pd.concat(all_prediction)

In [31]:
prediction=backtest(df,rr,predictor)

In [32]:
prediction

        actual  prediction  diff
3650      22.0        24.0   2.0
3651      24.0        23.0   2.0
3652      26.0        24.0   2.0
3653      26.0        24.0   2.0
3654      25.0        24.0   1.0
...        ...         ...   ...
115557    18.0        26.0   7.0
115558    25.0        19.0   6.0
115559    31.0        23.0   8.0
115560    28.0        27.0   1.0
115561     NaN        25.0   NaN

[111912 rows x 3 columns]

In [33]:
prediction.ffill(inplace=True)

In [34]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(prediction['actual'],prediction['prediction'])

2.9252090928586747

In [35]:
prediction['diff'].mean()

2.914102151690614

In [36]:
def pct_diff(old,new):
    return round((new-old)/old)

def compute_rolling(df,horizon,col):
    label=f'rolling_{horizon}_{col}'
    
    df[label]=round(df[col].rolling(horizon).mean())
    df[f"{label}_pct"]=round(pct_diff(df[label],df[col]))
    return df

rolling_horizons=[3,14]

for horizon in rolling_horizons:
    for col in ['temperature_celsius', 'wind_mph', 'pressure_mb', 'humidity']:
        df=compute_rolling(df,horizon,col)

In [37]:
df

,location_name,latitude,longitude,last_updated,temperature_celsius,condition_text,wind_mph,pressure_mb,precip_mm,humidity,...,rolling_3_humidity,rolling_3_humidity_pct,rolling_14_temperature_celsius,rolling_14_temperature_celsius_pct,rolling_14_wind_mph,rolling_14_wind_mph_pct,rolling_14_pressure_mb,rolling_14_pressure_mb_pct,rolling_14_humidity,rolling_14_humidity_pct
0,Ashoknagar,24.57,77.72,2023-08-29 10:45:00,27.5,partly cloudy,12.8,1008.0,0.0,67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Raisen,23.33,77.80,2023-08-29 10:45:00,27.5,sunny,9.6,1008.0,0.0,70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chhindwara,22.07,78.93,2023-08-29 10:45:00,26.3,partly cloudy,11.4,1009.0,0.0,70,...,69.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Betul,21.86,77.93,2023-08-29 10:45:00,25.6,cloudy,10.5,1009.0,0.0,76,...,72.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Hoshangabad,22.75,77.72,2023-08-29 10:45:00,27.2,cloudy,10.1,1009.0,0.0,74,...,73.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115557,Niwari,28.88,77.53,2024-03-30 21:45:00,29.0,mist,2.2,1011.0,0.0,45,...,42.0,0.0,28.0,0.0,7.0,-1.0,1011.0,0.0,56.0,-0.0
115558,Saitual,23.97,92.58,2024-03-30 21:45:00,18.3,clear,3.6,1014.0,0.0,79,...,48.0,1.0,28.0,-0.0,7.0,-0.0,1011.0,0.0,58.0,0.0
115559,Ranipet,12.93,79.33,2024-03-30 21:45:00,25.4,clear,6.3,1014.0,0.0,57,...,60.0,-0.0,27.0,-0.0,7.0,-0.0,1011.0,0.0,59.0,-0.0
115560,Tenkasi,8.97,77.30,2024-03-30 21:45:00,31.0,mist,2.2,1013.0,0.0,66,...,67.0,-0.0,27.0,0.0,6.0,-1.0,1011.0,0.0,62.0,0.0
115561,Pendra,21.93,74.15,2024-03-30 21:45:00,27.8,clear,6.7,1012.0,0.0,23,...,49.0,-1.0,28.0,-0.0,7.0,-0.0,1011.0,0.0,58.0,-1.0

In [38]:
df=df.iloc[14:,:]

In [39]:
df

,location_name,latitude,longitude,last_updated,temperature_celsius,condition_text,wind_mph,pressure_mb,precip_mm,humidity,...,rolling_3_humidity,rolling_3_humidity_pct,rolling_14_temperature_celsius,rolling_14_temperature_celsius_pct,rolling_14_wind_mph,rolling_14_wind_mph_pct,rolling_14_pressure_mb,rolling_14_pressure_mb_pct,rolling_14_humidity,rolling_14_humidity_pct
14,Satna,24.58,80.83,2023-08-29 10:45:00,30.1,partly cloudy,11.2,1007.0,0.0,58,...,63.0,-0.0,28.0,0.0,10.0,0.0,1008.0,-0.0,67.0,-0.0
15,Chhatarpur,24.90,79.60,2023-08-29 10:45:00,30.0,sunny,11.6,1007.0,0.0,60,...,61.0,-0.0,28.0,0.0,10.0,0.0,1008.0,-0.0,67.0,-0.0
16,Indore,22.72,75.83,2023-08-29 10:45:00,26.0,mist,11.9,1012.0,0.0,74,...,64.0,0.0,28.0,-0.0,10.0,0.0,1009.0,0.0,67.0,0.0
17,Ratlam,23.32,75.07,2023-08-29 10:45:00,26.5,partly cloudy,14.1,1009.0,0.0,64,...,66.0,-0.0,28.0,-0.0,10.0,0.0,1009.0,0.0,66.0,-0.0
18,Harda,22.33,77.10,2023-08-29 10:45:00,28.4,partly cloudy,12.5,1009.0,0.0,64,...,67.0,-0.0,28.0,0.0,10.0,0.0,1009.0,0.0,65.0,-0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115557,Niwari,28.88,77.53,2024-03-30 21:45:00,29.0,mist,2.2,1011.0,0.0,45,...,42.0,0.0,28.0,0.0,7.0,-1.0,1011.0,0.0,56.0,-0.0
115558,Saitual,23.97,92.58,2024-03-30 21:45:00,18.3,clear,3.6,1014.0,0.0,79,...,48.0,1.0,28.0,-0.0,7.0,-0.0,1011.0,0.0,58.0,0.0
115559,Ranipet,12.93,79.33,2024-03-30 21:45:00,25.4,clear,6.3,1014.0,0.0,57,...,60.0,-0.0,27.0,-0.0,7.0,-0.0,1011.0,0.0,59.0,-0.0
115560,Tenkasi,8.97,77.30,2024-03-30 21:45:00,31.0,mist,2.2,1013.0,0.0,66,...,67.0,-0.0,27.0,0.0,6.0,-1.0,1011.0,0.0,62.0,0.0
115561,Pendra,21.93,74.15,2024-03-30 21:45:00,27.8,clear,6.7,1012.0,0.0,23,...,49.0,-1.0,28.0,-0.0,7.0,-0.0,1011.0,0.0,58.0,-1.0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115548 entries, 14 to 115561
Data columns (total 27 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   location_name                       115548 non-null  object
 1   latitude                            115548 non-null  float64
 2   longitude                           115548 non-null  float64
 3   last_updated                        115548 non-null  datetime64[ns]
 4   temperature_celsius                 115548 non-null  float64
 5   condition_text                      115548 non-null  object
 6   wind_mph                            115548 non-null  float64
 7   pressure_mb                         115548 non-null  float64
 8   precip_mm                           115548 non-null  float64
 9   humidity                            115548 non-null  int64
 10  Target                              115547 non-null  float64
 11  rolling_3_temperature_celsius       115548 non-null  float64
 12  rolling_3_temperature_celsius_pct   115544 non-null  float64
 13  rolling_3_wind_mph                  115548 non-null  float64
 14  rolling_3_wind_mph_pct              115548 non-null  float64
 15  rolling_3_pressure_mb               115548 non-null  float64
 16  rolling_3_pressure_mb_pct           115548 non-null  float64
 17  rolling_3_humidity                  115548 non-null  float64
 18  rolling_3_humidity_pct              115548 non-null  float64
 19  rolling_14_temperature_celsius      115548 non-null  float64
 20  rolling_14_temperature_celsius_pct  115548 non-null  float64
 21  rolling_14_wind_mph                 115548 non-null  float64
 22  rolling_14_wind_mph_pct             115548 non-null  float64
 23  rolling_14_pressure_mb              115548 non-null  float64
 24  rolling_14_pressure_mb_pct          115548 non-null  float64
 25  rolling_14_humidity                 115548 non-null  float64
 26  rolling_14_humidity_pct             115548 non-null  float64
dtypes: datetime64[ns](1), float64(23), int64(1), object(2)
memory usage: 23.8+ MB

In [41]:
def expand_mean(df1):
    return df1.expanding(1).mean()
for col in ['temperature_celsius', 'wind_mph', 'pressure_mb', 'humidity']:
    df[f"month_avg_{col}"]=df[col].groupby(df['last_updated'].dt.month,group_keys=False).apply(expand_mean)
    df[f"day_avg_{col}"]=df[col].groupby(df['last_updated'].dt.day_of_year,group_keys=False).apply(expand_mean)

In [42]:
df

,location_name,latitude,longitude,last_updated,temperature_celsius,condition_text,wind_mph,pressure_mb,precip_mm,humidity,...,rolling_14_humidity,rolling_14_humidity_pct,month_avg_temperature_celsius,day_avg_temperature_celsius,month_avg_wind_mph,day_avg_wind_mph,month_avg_pressure_mb,day_avg_pressure_mb,month_avg_humidity,day_avg_humidity
14,Satna,24.58,80.83,2023-08-29 10:45:00,30.1,partly cloudy,11.2,1007.0,0.0,58,...,67.0,-0.0,30.100000,30.100000,11.200000,11.200000,1007.000000,1007.000000,58.000000,58.000000
15,Chhatarpur,24.90,79.60,2023-08-29 10:45:00,30.0,sunny,11.6,1007.0,0.0,60,...,67.0,-0.0,30.050000,30.050000,11.400000,11.400000,1007.000000,1007.000000,59.000000,59.000000
16,Indore,22.72,75.83,2023-08-29 10:45:00,26.0,mist,11.9,1012.0,0.0,74,...,67.0,0.0,28.700000,28.700000,11.566667,11.566667,1008.666667,1008.666667,64.000000,64.000000
17,Ratlam,23.32,75.07,2023-08-29 10:45:00,26.5,partly cloudy,14.1,1009.0,0.0,64,...,66.0,-0.0,28.150000,28.150000,12.200000,12.200000,1008.750000,1008.750000,64.000000,64.000000
18,Harda,22.33,77.10,2023-08-29 10:45:00,28.4,partly cloudy,12.5,1009.0,0.0,64,...,65.0,-0.0,28.200000,28.200000,12.260000,12.260000,1008.800000,1008.800000,64.000000,64.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115557,Niwari,28.88,77.53,2024-03-30 21:45:00,29.0,mist,2.2,1011.0,0.0,45,...,56.0,-0.0,23.314576,27.018635,5.973272,6.814576,1012.943754,1011.747232,44.733090,47.461255
115558,Saitual,23.97,92.58,2024-03-30 21:45:00,18.3,clear,3.6,1014.0,0.0,79,...,58.0,0.0,23.314271,27.002578,5.973128,6.808656,1012.943818,1011.751381,44.735178,47.519337
115559,Ranipet,12.93,79.33,2024-03-30 21:45:00,25.4,clear,6.3,1014.0,0.0,57,...,59.0,-0.0,23.314398,26.999632,5.973148,6.807721,1012.943883,1011.755515,44.735925,47.536765
115560,Tenkasi,8.97,77.30,2024-03-30 21:45:00,31.0,mist,2.2,1013.0,0.0,66,...,62.0,0.0,23.314866,27.006972,5.972918,6.799266,1012.943886,1011.757798,44.737220,47.570642
115561,Pendra,21.93,74.15,2024-03-30 21:45:00,27.8,clear,6.7,1012.0,0.0,23,...,58.0,-1.0,23.315140,27.008425,5.972962,6.799084,1012.943828,1011.758242,44.735896,47.525641

In [43]:
predictor=df.columns[~df.columns.isin(['location_name','latitude','condition_text','longitude','last_updated','precip_mm','Target'])]

In [44]:
predictor

Index(['temperature_celsius', 'wind_mph', 'pressure_mb', 'humidity',
       'rolling_3_temperature_celsius', 'rolling_3_temperature_celsius_pct',
       'rolling_3_wind_mph', 'rolling_3_wind_mph_pct', 'rolling_3_pressure_mb',
       'rolling_3_pressure_mb_pct', 'rolling_3_humidity',
       'rolling_3_humidity_pct', 'rolling_14_temperature_celsius',
       'rolling_14_temperature_celsius_pct', 'rolling_14_wind_mph',
       'rolling_14_wind_mph_pct', 'rolling_14_pressure_mb',
       'rolling_14_pressure_mb_pct', 'rolling_14_humidity',
       'rolling_14_humidity_pct', 'month_avg_temperature_celsius',
       'day_avg_temperature_celsius', 'month_avg_wind_mph', 'day_avg_wind_mph',
       'month_avg_pressure_mb', 'day_avg_pressure_mb', 'month_avg_humidity',
       'day_avg_humidity'],
      dtype='object')

In [45]:
location=input("Enter the location you want to search \n")
df[df['location_name']==location]

Enter the location you want to search
pune

Empty DataFrame
Columns: [location_name, latitude, longitude, last_updated, temperature_celsius, condition_text, wind_mph, pressure_mb, precip_mm, humidity, Target, rolling_3_temperature_celsius, rolling_3_temperature_celsius_pct, rolling_3_wind_mph, rolling_3_wind_mph_pct, rolling_3_pressure_mb, rolling_3_pressure_mb_pct, rolling_3_humidity, rolling_3_humidity_pct, rolling_14_temperature_celsius, rolling_14_temperature_celsius_pct, rolling_14_wind_mph, rolling_14_wind_mph_pct, rolling_14_pressure_mb, rolling_14_pressure_mb_pct, rolling_14_humidity, rolling_14_humidity_pct, month_avg_temperature_celsius, day_avg_temperature_celsius, month_avg_wind_mph, day_avg_wind_mph, month_avg_pressure_mb, day_avg_pressure_mb, month_avg_humidity, day_avg_humidity]
Index: []

[0 rows x 35 columns]

In [48]:
import tkinter as tk
from tkinter import ttk
from tkinter import messagebox
import requests

class WeatherBot:
    def __init__(self):
        self.responses = {
            "hi": "Hello! How can I help you?",
            "hello": "Hi there! What can I assist you with?",
            "help": "Sure, I can help you with weather predictions. Just enter the city name!",
            "thanks": "You're welcome! If you need anything else, feel free to ask."
        }

    def get_response(self, message):
        # Convert message to lowercase for case-insensitive matching
        message = message.lower()
        return self.responses.get(message,"OK This is the information of city that you Enterd")

    def get_weather(self, city):
        api_key = "734be55b262f9e7726b4ef402bb52931"  # Replace with your OpenWeatherMap API key
        url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            weather_info = f"Weather: {data['weather'][0]['main']}\nTemperature: {data['main']['temp']} °C\nHumidity: {data['main']['humidity']} g/kg\nPressure: {data['main']['pressure']} mb\nWind Speed: {data['wind']['speed']} mph"
            prediction_info = f"Predictive_Temperature: {df[df['location_name']==city]['rolling_14_temperature_celsius'].iloc[-1]} °C\nHumidity: {df[df['location_name']==city]['rolling_14_humidity'].iloc[-1]} g/kg\nPredictive_WindSpeed: {df[df['location_name']==city]['rolling_14_wind_mph'].iloc[-1]} mph\nPredictive_Pressure: {df[df['location_name']==city]['rolling_14_pressure_mb'].iloc[-1]} mb"

            insert_message(f"User: {city}")
            insert_message(f"Bot: {weather_info}")
            insert_message(f"Bot: {prediction_info}")
#         else:
#             messagebox.showerror("Error", "Failed to fetch weather data")

def send_message():
    user_message = city_entry.get()
    insert_message(f"You: {user_message}")

    bot_response = bot.get_response(user_message)
    insert_message(f"Bot: {bot_response}")

    if user_message.strip().replace(" ", "").isalpha():
        bot.get_weather(user_message.strip())

def insert_message(message):
    chat_box.config(state=tk.NORMAL)
    chat_box.insert(tk.END, message + "\n")
    chat_box.config(state=tk.DISABLED)

# Create main window
root = tk.Tk()
root.title("Weather Prediction Chat")

# Define colors
bg_color = "Sky Blue"  # Purple background color
button_color = "Gold"  # Gold button color
text_color = "Black"  # Black text color

# Set background color
root.config(bg=bg_color)

# Create chat frame
chat_frame = ttk.Frame(root)
chat_frame.pack(padx=20, pady=20)

# Create chat box
chat_box = tk.Text(chat_frame, width=50, height=20, wrap=tk.WORD, state=tk.DISABLED)
chat_box.pack(side=tk.LEFT)

# Create scrollbar
scrollbar = ttk.Scrollbar(chat_frame, orient=tk.VERTICAL, command=chat_box.yview)
scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
chat_box.config(yscrollcommand=scrollbar.set)

# Create entry frame
entry_frame = ttk.Frame(root, padding=(20, 10))
entry_frame.pack()

# Create label
label = ttk.Label(entry_frame, text="Say something:", background=bg_color, foreground=text_color, font=("Helvetica", 12))
label.grid(row=0, column=0, padx=5, pady=5, sticky="w")

# Create entry
city_entry = ttk.Entry(entry_frame, width=30)
city_entry.grid(row=0, column=1, padx=5, pady=5, sticky="w")

# Create button
send_button = ttk.Button(entry_frame, text="Send", command=send_message, style="TButton", cursor="hand2")
send_button.grid(row=0, column=2, padx=5, pady=5, sticky="e")

# Initialize WeatherBot
bot = WeatherBot()

# Run the application
root.mainloop()